### ISSUE TITLE
create a controller to provides the business logic of product tags with barcode lib

### ISSUE THREAD

**Issue by bidwolf** [bidwolf/pro-bar#3]
# Requirements

We have to create an encapsulated module to provide for the product-tag route with the right way to create the bar code based on the product code provided.

Due to this, what we need is to use the [python-barcode](https://pypi.org/project/python-barcode/) lib to create them.

## Tasks

- [x] Create the controller using the driver created at #1 
- [x] Use the controller on the view

**Comment by bidwolf** [comment]
#1 Depends on it.

**Comment by bidwolf** [comment]
# Updates

The controller doesn't handle errors correctly, this is problematic because the user can send any type of entry to the endpoint also can send nothing, breaking the code.

The new task is to handle errors by validating the entry product code.

- [ ] validate product code on the business logic
